### ISSUE TITLE
[Resource] es_ALL

### ISSUE THREAD

**Issue by Dorzar** [bl4ckscor3/GlobalXP#1]
Enjoy it ^^
The translation is equal for es_ES, es_MX, es_VE, es_AR, etc.

//Translated by: Dorzar / VeryHardChamp
//Act.: 31/07/2017
tile.xp_block.name=Almacenador de EXP
waila.body=%s niveles almacenados

**Comment by bl4ckscor3** [comment]
Thanks!

**Comment by bl4ckscor3** [comment]
Mind translating the new strings found [here](https://github.com/bl4ckscor3/GlobalXP/blob/7f197d562e9dec7330f7bebabf6b3fbdcc68e41a/src/main/resources/assets/globalxp/lang/en_US.lang#L3-L6)? :)

Also if you want to keep translating (not sure if there will be anything, but just in case) please contact me on CurseForge to stay in contact, that way we don't need to use this issue as a chat!

**Comment by Dorzar** [comment]
//Translated by: Dorzar / VeryHardChamp
//Act.: 09/08/2017
tile.xp_block.name=Almacenador de EXP
waila.body=%s niveles guardados
globalxp.config.spinspeed=Velocidad de giro
globalxp.config.spinspeed.tooltip=¿Qué tan rápido debe girar la esmeralda? (multiplica la velocidad predeterminada).
globalxp.config.bobspeed=Velocidad de animación
globalxp.config.bobspeed.tooltip=¿Qué tan rápido la esmeralda debe hacer la animación de subir y bajar? (multiplica la velocidad predeterminada).

Yep i want keep translating this, no problem :)

**Comment by bl4ckscor3** [comment]
Cool! Please ship me a message [here](https://minecraft.curseforge.com/members/bl4ckscor3).
