### ISSUE TITLE
XP Block drops on destruction in creative

### ISSUE THREAD

**Issue by ghost** [bl4ckscor3/GlobalXP#10]
### **Version**
globalxp-1.12.x-v1.4.jar
globalxp-1.13.2-v1.4.jar

### **Expected behavior**
Blocks don't drop anything on destruction.

### **Actual behaviour**
Issue title says it all, but just in case.
![2019-03-03_09 48 19](https://user-images.githubusercontent.com/34396343/53692522-40a00e80-3d9a-11e9-81e4-4afb73640631.png)

**Comment by bl4ckscor3** [comment]
That's intended so you don't accidentally lose XP when you are in creative mode temporarily. The behavior for shulker boxes is the same.

I'll fix the block dropping when it's empty, though.

**Comment by ghost** [comment]
> That's intended so you don't accidentally lose XP when you are in creative mode temporarily. The behavior for shulker boxes is the same.
> 
> I'll fix the block dropping when it's empty, though.

Yeah, that's what I thought at first.
As I remember, there's similar thing with capacitor from EnderIO, it saves its state as dropped item. but only if destroyed by player in survival.
