### ISSUE TITLE
Suggestion: Comparator output based on XP stored

### ISSUE THREAD

**Issue by D-Fink** [bl4ckscor3/GlobalXP#17]
Configurable xp to redstone redstone power.
i.e.
500xp - 1 redstone signal
1000xp - 2 redstone signal
etc

**Comment by bl4ckscor3** [comment]
You mean a comparator detects the amount of XP in the block and then gives off a redstone signal based on the amount of XP it detected?

**Comment by D-Fink** [comment]
Correct
