### ISSUE TITLE
[1.15.2] Crash on launch with OneProbe

### ISSUE THREAD

**Issue by dierks-m** [bl4ckscor3/GlobalXP#19]
Experienced on
Minecraft 1.15.2
Forge 31.0.1
GlobalXP 1.4.11

Adding TOP causes the game to not start due to an IMC issue. I'm not 100% sure if this is to blame on GlobalXP.

[Crash Log](https://pastebin.com/wgpcvkzq)

**Comment by bl4ckscor3** [comment]
Fixed in the Global XP release for Minecraft 1.15.2.

**Comment by Gbergz** [comment]
This happens again but on the 1.16.1 release with The One Probe.

**Comment by bl4ckscor3** [comment]
Yes, I know. It has already been fixed shortly after you posted. https://www.curseforge.com/minecraft/mc-mods/global-xp/files/2999324
