### ISSUE TITLE
[Suggestion] Store XP amount in block

### ISSUE THREAD

**Issue by PurpleHel** [bl4ckscor3/GlobalXP#2]
Right now, if you break the global XP block, even with silk touch, it loses all the stored XP. What if you used NBT or something to make the stored XP persistent?

**Comment by bl4ckscor3** [comment]
I have that planned for the next version, but as I'm waiting for a pull request currently I put that on hold. I'll wait for it a few more days and continue working on this if no pr has been submitted.

**Comment by PurpleHel** [comment]
Sweet!

**Comment by bl4ckscor3** [comment]
Merged #5, so I can continue working on the next version. I will update probably this weekend.
