### ISSUE TITLE
Redstone Control?

### ISSUE THREAD

**Issue by papaworld** [bl4ckscor3/GlobalXP#25]
Would it be possible to have normal/inverted/ignore redstone control with a possible comparator output.
- ThanX

**Comment by bl4ckscor3** [comment]
The comparator already works with the XP Block. It will show how much XP is stored in it. By default, a signal length of 15 will mean that there are 30 levels (1395 XP) stored in the XP Block. You can change this value in the config file.

I don't think that a redstone input for the block is needed, or what it would be even used for.

**Comment by papaworld** [comment]
I've created an Experience Orb Generator. The orbs absorbed would go to 1 of 3 machines that would pickup the orbs, the 3 machines produce:
1) Bottles o Enchanting
2) XP storage (your mod)
3) Essence (Industrial Foregoing)

The machines for Bottles o Enchanting and Essence are redstone controlled manually for the desired output.
Global XP is pushed in and out of the pickup range with a piston also with manual on/off button (not ideal pickup). Otherwise, I have to break and store the Global XP block when other outputs are desired.
ThanX for your consideration. Great mod!! Very helpful.

**Comment by bl4ckscor3** [comment]
Ah, I see. You want the redstone input to toggle whether the XP Block can pickup XP orbs. I can add that. Sorry for my ignorance before.

**Comment by papaworld** [comment]
No problem, Sir... I should have clarified the functional application. I much appreciate your consideration willingness and producing a super mod usable at near-vanilla level to high-end tech level. Thank you.

**Comment by bl4ckscor3** [comment]
This feature is now available in v1.7 of Global XP.

**Comment by papaworld** [comment]
bl4ckscor3, thank so much for the redstone control addition to your mod. Play-On!!
