### ISSUE TITLE
Error with The One Probe when i start it in 1.17.1

### ISSUE THREAD

**Issue by MrScautHD** [bl4ckscor3/GlobalXP#29]
HEy i have a Error with The One Probe when i start it in 1.17.1 with your mod (without your mod works fine, i hope you can fix it :D)

**Comment by bl4ckscor3** [comment]
What is the error? Please always included a crash report or log file (like latest.log) when reporting these things.

**Comment by bl4ckscor3** [comment]
Ah, well, I figured it out. There's a new TOP version with a breaking API change. Global XP v1.8.3 will fix that.

**Comment by MrScautHD** [comment]
oh sry (i have forgoten the log)
but thx now works :D
