### ISSUE TITLE
XP is stored linearly, unlike how XP works.

### ISSUE THREAD

**Issue by majijn** [bl4ckscor3/GlobalXP#3]
I just added the mod to my pack as I was missing a way to store XP, and i love how minimalistic this is, but currenly it makes getting 30 levels too easy,
the fact that it stores XP linearly means the fastest way to get to level 30 is to store your first level 30 times,
210 xp is not even close to the close to the 1400 xp you need to get to lvl 30 normally

**Comment by bl4ckscor3** [comment]
I am completely aware of this. The mod was never intended to be balanced or fair, as it has been made for private use. I didn't even want to publish it at first, but decided ultimately for it. I am unsure wether I will allow the storage of 'normal' XP or not.

**Comment by CplPibald** [comment]
Here is a PR that solves this issue by changing the block from storing levels to storing XP.  https://github.com/bl4ckscor3/GlobalXP/pull/4

**Comment by bl4ckscor3** [comment]
Merged #5, so this change is now in the mod. I will update probably this weekend.
