### ISSUE TITLE
[1.18.1 Forge] Block Does Not Store XP Data When Broken

### ISSUE THREAD

**Issue by Zedrimar** [bl4ckscor3/GlobalXP#31]
Tested with: 
Forge 39.0.7
Global XP: 1.9

How to reproduce:
Put some experience into the xp storage block and then break the block. 0 levels will be stored. Tested with silk touch just in case maybe there was something changed so that it only stores with silk when picked up, but that isn't the case.

I am not entirely sure what is causing this, I think forge may have changed how NBT data is stored on blocks when picked up.

**Comment by bl4ckscor3** [comment]
Thanks for reporting! It was indeed caused by a change in how block entities store NBT data in general.
