### ISSUE TITLE
[1.18.1 Forge] Game Crash, When Break XP Block With XP Stored

### ISSUE THREAD

**Issue by Zeee-eeek** [bl4ckscor3/GlobalXP#32]
Forge: 39.1.0
Global XP: globalxp-1.18.1-1.9.1.jar
JVM Arguments:
-Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Settings: Everything default, since I've tested this in a clean mc profile with only forge and global xp as mods.

Crashlog:
`The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag bl4ckscor3.mod.globalxp.xpblock.XPBlockEntity.save(net.minecraft.nbt.CompoundTag)'
Exit-Code: -1`

Reproduce:
It happens on XP Block with XP's stored. Then break it with anything. Even with bare hands in creative. It crashes the game immediately.

> Full Crashlog:
> `---- Minecraft Crash Report ----
> // Hi. I'm Minecraft, and I'm a crashaholic.
> 
> Time: 20.03.22, 15:40
> Description: Exception in server tick loop
> 
> java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag bl4ckscor3.mod.globalxp.xpblock.XPBlockEntity.save(net.minecraft.nbt.CompoundTag)'
> 	at bl4ckscor3.mod.globalxp.xpblock.XPBlock.m_6810_(XPBlock.java:171) ~[globalxp-1.18.1-1.9.jar%2352!/:1.9] {re:classloading}
> 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60753_(BlockBehaviour.java:671) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:236) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.world.level.Level.m_6933_(Level.java:202) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.world.level.Level.m_7731_(Level.java:179) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraftforge.common.extensions.IForgeBlock.onDestroyedByPlayer(IForgeBlock.java:166) ~[forge-1.18.1-39.1.0-universal.jar%2357!/:?] {re:classloading}
> 	at net.minecraftforge.common.extensions.IForgeBlockState.onDestroyedByPlayer(IForgeBlockState.java:122) ~[forge-1.18.1-39.1.0-universal.jar%2357!/:?] {re:classloading}
> 	at net.minecraft.server.level.ServerPlayerGameMode.removeBlock(ServerPlayerGameMode.java:268) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:251) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading}
> 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2353!/:?] {re:classloading,pl:accesstransformer:B}
> 	at java.lang.Thread.run(Thread.java:833) [?:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.18.1
> 	Minecraft Version ID: 1.18.1
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 2543613312 bytes (2425 MiB) / 4294967296 bytes (4096 MiB) up to 8589934592 bytes (8192 MiB)
> 	CPUs: 24
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
> 	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
> 	Microarchitecture: Zen 3
> 	Frequency (GHz): 3,70
> 	Number of physical packages: 1
> 	Number of physical CPUs: 12
> 	Number of logical CPUs: 24
> 	Graphics card #0 name: NVIDIA GeForce GTX 1080
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 	Graphics card #0 VRAM (MB): 4095,00
> 	Graphics card #0 deviceId: 0x1b80
> 	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
> 	Memory slot #0 capacity (MB): 16384,00
> 	Memory slot #0 clockSpeed (GHz): 3,60
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 16384,00
> 	Memory slot #1 clockSpeed (GHz): 3,60
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 37546,35
> 	Virtual memory used (MB): 20569,05
> 	Swap memory total (MB): 4864,00
> 	Swap memory used (MB): 334,91
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Server Running: true
> 	Player Count: 1 / 8; [ServerPlayer['Zeeeeeek'/169, l='ServerLevel[New World]', x=-170.40, y=65.00, z=251.50]]
> 	Data Packs: vanilla, mod:forge, mod:globalxp
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
> 	ModLauncher: 9.1.0+9.1.0+main.6690ee51
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		 mixin PLUGINSERVICE 
> 		 eventbus PLUGINSERVICE 
> 		 object_holder_definalize PLUGINSERVICE 
> 		 runtime_enum_extender PLUGINSERVICE 
> 		 capability_token_subclass PLUGINSERVICE 
> 		 accesstransformer PLUGINSERVICE 
> 		 runtimedistcleaner PLUGINSERVICE 
> 		 mixin TRANSFORMATIONSERVICE 
> 		 fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		javafml@null
> 	Mod List: 
> 		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		forge-1.18.1-39.1.0-universal.jar                 |Forge                         |forge                         |39.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
> 		globalxp-1.18.1-1.9.jar                           |Global XP                     |globalxp                      |1.9                 |DONE      |Manifest: NOSIGNATURE
> 	Crash Report UUID: 870246df-8465-450f-904b-12ab9e37dd78
> 	FML: 39.1
> 	Forge: net.minecraftforge:39.1.0`

**Comment by bl4ckscor3** [comment]
I can't reproduce this with the same versions as you are using. And looking at the code and jar file, this shouldn't happen in the first place.
Also, I no longer support Minecraft 1.18.1 in favor of 1.18.2. Please try it there as well, although I can't reproduce it with that either (Forge 40.0.19, Global XP 1.9.1).

**Comment by Zeee-eeek** [comment]
Thank you for responding. This helps me out a bit to sort the problem out, that may occur on system specific possibilities.
A friend of mine has the same issue, as I have. He also tried new mc-profile with only forge and this mod version.
We are trying now some ideas out to find the source of the issue.

Things, that I already tried (with forge 39.1.0 and globalxp-1.18.1-1.9.1.jar):
- remove and reinstall Minecraft and the MS Minecraft Launcher completely
- try mc-profile on the default appdata install-directory, instead my favorited custom install directory
- updated Java to jre-8u321-windows-x64

Error still occured.

But, as I write you right at this moment my friend wrote me he figured out, it must be the Forge Version:
Crash doesnt happen on Forge 39.0.5 (**not** 39.0.**50**)

Doesn't crash also on my client either with 39.0.5.
