### ISSUE TITLE
Allow Renaming/Nametagging the XP Block

### ISSUE THREAD

**Issue by jebug29** [bl4ckscor3/GlobalXP#40]
Hello! Currently if the XP Block is named on an anvil, it loses that name after it's placed and then picked up. I was wondering if it would be possible to allow permanent naming of the block, and possibly displaying it in the visible tag when looking at it, as this would be helpful for multiplayer servers.

Thanks!

**Comment by bl4ckscor3** [comment]
This is now available in v1.11.

**Comment by jebug29** [comment]
Hooray! Thanks!
