### ISSUE TITLE
Item duping with valkyrien skies.

### ISSUE THREAD

**Issue by uczpre** [bl4ckscor3/GlobalXP#41]
the XP block in the "ship" (which is just an entity) will make drops of itself without breaking (thus duping itself and all the xp it contains) when the ship is assembled/disassembled.
pls fix :)

for easy ship assemble/dissassembly use the mod Eureka

**Comment by uczpre** [comment]
Are you aware whats causing this behavior (yet) ?

**Comment by minecraft552** [comment]
It's caused by the drop code in onRemove event, https://github.com/bl4ckscor3/GlobalXP/blob/neoforge/1.20.4/src/main/java/bl4ckscor3/mod/globalxp/xpblock/XPBlock.java#L186-L187

**Comment by uczpre** [comment]
OMG NO WAY :0

**Comment by minecraft552** [comment]
I have an idea for a fix in mind, I'll write a PR today

**Comment by uczpre** [comment]
ur cool ,😎😎😎
