### ISSUE TITLE
XP Block working just not for me

### ISSUE THREAD

**Issue by BlindedByBriars** [bl4ckscor3/GlobalXP#42]
Hi! I am in a server and your mod is being used quite often however I am the only player that is unable to use the XP Block. Everyone else has used the XP Block I have been trying to use and I have even tried crafting new ones to try in different spots but to no avail. Shift clicking with both mouse buttons, changing key bindings to try and fix it, and even restarting my computer is not helping and I dont get it. If you could find any way to help me I would be grateful.

**Comment by bl4ckscor3** [comment]
Sounds like you may be using a mod that no one else in the server uses, which interferes with the controls. What mods do you have installed?

As an example (which may not apply to you), Carry On may do this, and the way to fix it with that mod is to add the XP block to the exclusion config of that mod.

**Comment by BlindedByBriars** [comment]
Its all the same, its my first time even playing modded Minecraft and I downloaded the pack sent to me. With Carry On (because that was an issue in the beginning that another player pointed out) I changed the key bindings for it. I have even gone through key binds and changed every conflicting key

**Comment by bl4ckscor3** [comment]
Again, what mods do you have installed?

**Comment by BlindedByBriars** [comment]
Im currently playing Cisco’s Adventure RPG. But I have found the problem. It is because I picked the Plantaemancer Origin. Thank you for trying to help me anyways
