### ISSUE TITLE
[1.21-NeoForge] Jade support does not work

### ISSUE THREAD

**Issue by Gbergz** [bl4ckscor3/GlobalXP#46]
[Suggestion-1.21-NeoForge] Add Jade support. (showing total levels stored in jade tooltip)
![ss](https://github.com/user-attachments/assets/3fb7f489-9c13-438a-ae63-da594e41a990)

**Comment by bl4ckscor3** [comment]
Support for WAILA/HWYLA/Jade has been there since day one. I'm not sure why it doesn't work.
It also seems like the nameplate doesn't render.

**Comment by Gbergz** [comment]
Hm, yeah it works when I tested with WTHIT: https://www.curseforge.com/minecraft/mc-mods/wthit-forge , but currently not with Jade.

**Comment by bl4ckscor3** [comment]
I can't reproduce this with Jade [15.1.8](https://www.curseforge.com/minecraft/mc-mods/jade/files/5639932). Perhaps this was caused by a regression in Jade that has since been fixed.

**Comment by Gbergz** [comment]
Tested with Jade 15.1.8 right now, and it still doesn't show. Tested with just Jade v15.1.8 & Global XP v1.11

![ss1](https://github.com/user-attachments/assets/cf935d3a-b24f-4be5-90bc-958d7b6aa899)

![ss2](https://github.com/user-attachments/assets/b057fffd-2112-480f-8b32-30595c2fec2b)

**Comment by bl4ckscor3** [comment]
Hm, ok. Then Global XP v1.12 will fix it, because testing it with a built version of that works fine. I'm not sure about why it's fixed there though.
I'll release the update soon.

**Comment by Gbergz** [comment]
![ss](https://github.com/user-attachments/assets/ec8b9ebb-c94a-498e-8fb9-a1ed39aac3dc)
All fixed in latest version, thanks!
